config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :costs

  resources :incomes

  resources :all

  root 'costs#index'

  get 'costs' => 'costs#show'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :user
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :costs
  has_many :incomes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/all_controller.rb
class AllController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @incomes = current_user.incomes
    @costs = current_user.costs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  protect_from_forgery with: :exception

  private

  def record_not_found
    render plain: "404 Not Found", status: 404
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
  end

  def show
    @costs = current_user.costs
  end

  def new
    @cost = Cost.new
  end

  def create
    @cost = current_user.costs.build(cost_params)
    if @cost.save
      flash[:success] = "Added"
      redirect_to '/costs/costs'
    else
      render 'costs/new'
    end
  end

  def destroy
  @cost = Cost.find(params[:id])
  @cost.destroy
  redirect_to :root
  end

  private

  def cost_params
    params.require(:cost).permit(:title, :amount)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def all
    @incomes = current_user.incomes
    @costs = current_user.costs
  end

  def show
    @incomes = current_user.incomes
  end

  def new
    @income = Income.new
  end

  def create
    @income = current_user.incomes.build(income_params)
    if @income.save
      flash[:success] = "Added"
      redirect_to '/incomes/show'
    else
      render 'incomes/new'
    end
  end

  def destroy
  @income = Income.find(params[:id])
  @income.destroy
  redirect_to :root
  end

  private

  def income_params
    params.require(:income).permit(:title, :amount)
  end
end

app/controllers/registrations_controller_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/registrations_controller_helper.rb
module RegistrationsControllerHelper
end

app/views/all/show.html.erb
<div class="slidershow">
</div>

<div class="container">
  <h1 class="allcosts">Your Disposable Income! - $<%= Income.where(user_id: @current_user.id).sum('amount') - Cost.where(user_id: @current_user.id).sum('amount') %>/month</h1>
</div>
<% if (Income.where(user_id: @current_user.id).sum('amount') - Cost.where(user_id: @current_user.id).sum('amount')) > 200 %>
<div class="container gif">
  <h2> Your Income is over $1000!</h2>
  <img src="http://gifsec.com/wp-content/uploads/GIF/2014/03/Happy-Success-GIF.gif?gs=a">
</div>
<% end %>

<% if (Income.where(user_id: @current_user.id).sum('amount') - Cost.where(user_id: @current_user.id).sum('amount')) < 500 %>
<div class="container gif">
  <h2> Your disposable income is under $200 :(</h2>
  <img src="https://media.giphy.com/media/qPuA1KdbOt6QU/giphy.gif">
</div>
<% end %>

app/views/costs/index.html.erb
<div class="slider">
  <h1>Determine Your Disposabl Income</h1>
  <div class="getstarted">
    <a href="/users/sign_up"><h3>Get Started</h3></a>
  </div>
</div>

<div class="container gif">
  <h2>How much money do you have to throw around?</h2>
<img src="https://media.giphy.com/media/8zuHuiw0RwMVy/giphy.gif">
</div>

app/views/costs/new.html.erb
<div class="slidershow">
  <h1>Determine Your Disposabl Income</h1>
</div>
<div class="container">
  <div class="costcontainer col-xs-12 col-sm-8 col-md-6 col-md-offset-3">
    <div class="form-box">
      <%= image_tag "square.gif" %>
      <h2>Add New Costs</h2>
      <%= render "layouts/form_errors", object: @cost %>
      <%= form_for @cost do |f| %>
        <div class="field">
          <%= f.label :new_cost %>
          <%= f.text_field :title, autofocus: true %>
        </div>
        <div class="field">
          <%= f.label :amount %>
          <%= f.text_field :amount, autofocus: true %>
        </div>
        <div class="field signup">
          <%= f.submit "Cost" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/costs/show.html.erb
<div class="slidershow">
  <h1>Determine Your Disposabl Income</h1>
</div>
<div class="container">
  <h1 class="allcosts">All Monthly Costs</h1>
  <div class="costcontainer col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="form-box">
    <table class="costtable">
      <tr class="costrow headinrow">
        <th class="costdata">Title</th>
        <th class="costdata">Amount</th>
        <th class="costdata"></th>
      </tr>
    <% @costs.each do |cost| %>
      <tr class="<%= cycle('even', 'odd') -%> costrow">
        <td class="costdata"><%= cost.title %></td>
        <td class="costdata"><%= cost.amount %></td>
        <td class="costdata"><div class="btn-delete"><%= link_to "Remove", cost, method: :delete, data: { confirm: "Are you sure?" } %></div></td>
      </tr>
    <% end %>
    <tr class="costrow">
      <td class="subtotal"><strong>Subtotal:</strong></td>
      <td class="subtotal"><strong><%= Cost.where(user_id: @current_user.id).sum('amount') %></strong></td>
      <td></td>
    </tr>
    </table>
    <br>
    <div class="btn-upload">
    <%= link_to "Add Cost", new_cost_path %>
  </div>
  </div>
</div>
</div>

app/views/incomes/all.html.erb
<div class="slidershow">
</div>

<div class="container">
  <h1 class="allcosts">All Monthly Income</h1>
  <div class="costcontainer col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="form-box">
    <table class="costtable">
      <tr class="costrow headinrow">
        <th class="costdata">Title</th>
        <th class="costdata">Amount</th>
        <th class="costdata"></th>
      </tr>
    <% @incomes.each do |income| %>
      <tr class="<%= cycle('even', 'odd') -%> costrow">
        <td class="costdata"><%= income.title %></td>
        <td class="costdata"><%= income.amount %></td>
        <td class="costdata"><div class="btn-delete"><%= link_to "Remove", income, method: :delete, data: { confirm: "Are you sure?" } %></div></td>
      </tr>
    <% end %>
    <tr class="costrow">
      <td class="subtotal"><strong>Subtotal:</strong></td>
      <td class="subtotal"><strong><%= Income.where(user_id: @current_user.id).sum('amount') %>/month</strong></td>
      <td></td>
    </tr>
    </table>
    <br>
    <div class="btn-upload">
    <%= link_to "Add Cost", new_cost_path %>
  </div>
  </div>
</div>
</div>

<div class="container">
  <h1 class="allcosts">All Monthly Costs</h1>
  <div class="costcontainer col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="form-box">
    <table class="costtable">
      <tr class="costrow headinrow">
        <th class="costdata">Title</th>
        <th class="costdata">Amount</th>
        <th class="costdata"></th>
      </tr>
    <% @costs.each do |cost| %>
      <tr class="<%= cycle('even', 'odd') -%> costrow">
        <td class="costdata"><%= cost.title %></td>
        <td class="costdata"><%= cost.amount %></td>
        <td class="costdata"><div class="btn-delete"><%= link_to "Remove", cost, method: :delete, data: { confirm: "Are you sure?" } %></div></td>
      </tr>
    <% end %>
    <tr class="costrow">
      <td class="subtotal"><strong>Subtotal:</strong></td>
      <td class="subtotal"><strong><%= Cost.where(user_id: @current_user.id).sum('amount') %>/month</strong></td>
      <td></td>
    </tr>
    </table>
    <br>
    <div class="btn-upload">
    <%= link_to "Add Cost", new_cost_path %>
  </div>
  </div>
</div>
</div>

app/views/incomes/new.html.erb
<div class="slidershow">
  <h1>Determine Your Disposabl Income</h1>
</div>
<div class="container">
  <div class="costcontainer col-xs-12 col-sm-8 col-md-6 col-md-offset-3">
    <div class="form-box">
      <%= image_tag "square.gif" %>
      <h2>Add Your Income</h2>
      <%= render "layouts/form_errors", object: @income %>
      <%= form_for @income do |f| %>
      <div class="field">
        <%= f.label :new_income_source %>
        <%= f.text_field :title, autofocus: true %>
      </div>
        <div class="field">
          <%= f.label :income %>
          <%= f.text_field :amount, autofocus: true %>
        </div>
        <div class="field signup">
          <%= f.submit "Income" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/incomes/show.html.erb
<div class="slidershow">
</div>

<div class="container">
  <h1 class="allcosts">All Monthly Income</h1>
  <div class="costcontainer col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="form-box">
    <table class="costtable">
      <tr class="costrow headinrow">
        <th class="costdata">Title</th>
        <th class="costdata">Amount</th>
        <th class="costdata"></th>
      </tr>
    <% @incomes.each do |income| %>
      <tr class="<%= cycle('even', 'odd') -%> costrow">
        <td class="costdata"><%= income.title %></td>
        <td class="costdata"><%= income.amount %></td>
        <td class="costdata"><div class="btn-delete"><%= link_to "Remove", income, method: :delete, data: { confirm: "Are you sure?" } %></div></td>
      </tr>
    <% end %>
    <tr class="costrow">
      <td class="subtotal"><strong>Subtotal:</strong></td>
      <td class="subtotal"><strong><%= Income.where(user_id: @current_user.id).sum('amount') %>/month</strong></td>
      <td></td>
    </tr>
    </table>
    <br>
    <div class="btn-upload">
    <%= link_to "Add Income", new_income_path %>
  </div>
  </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footerwrap">
	 	<div class="container">
		 	<div class="row">
		 		<div class="col-lg-12">
		 			<h4>About Disposabl</h4>
		 			<div class="hline-w"></div>
		 			<p>We help you determine how much monthly disposable income you really have.</p>
		 		</div>

		 		</div>


		 	</div><! --/row -->
	 	</div><! --/container -->
	 </div><! --/footerwrap -->

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.singularize %> from being saved:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="logo-responsive">
      <a class="navbar-brand " href="/"><%= image_tag "disposabl-logo.png" %></a>
    </div>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/costs/show"><i class="fa fa-credit-card"></i> My Costs</a></li>
        <li><a href="/incomes/show"><i class="fa fa-suitcase"></i> My Income</a></li>
        <li><a href="/all/show"><i class="fa fa-money"></i> My Disposable Income</a></li>
      </ul>
      <ul class="pull-right nav navbar-nav">
        <li class="btn btn-theme">
          <% if user_signed_in? %>
          <li>
            <div class="dropdown">

                <button class="avatarsmall dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <%= image_tag 'square.gif' %>
                </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li>
                <%= link_to('Edit Profile', edit_user_registration_path) %>
              </li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
            </ul>
            </div>
          </li>
          <li class="mobilelogout">
                <%= link_to('Edit Profile', edit_user_registration_path) %>
              </li>
          <li class="mobilelogout">
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
          <% else %>
        <li class="btn btn-theme">
          <%= link_to('Sign Up', new_user_registration_path)  %>
        </li>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
          <% end %>
        </li>


    </ul>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Disposabl</title>
  <meta name="description" content="Disposabl">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', '//fonts.googleapis.com/css?family=Raleway' %>
    <%= favicon_link_tag 'square.gif' %>
</head>
<body>
<%= render "layouts/header.html.erb" %>
<% if notice %>
      <p class="alerttop alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alerttop alert alert-danger"><%= alert %></p>
    <% end %>
<%= yield %>
<%= render "layouts/footer.html.erb" %>
</body>
</html>